---
driver:
  name: ec2
  availability_zone: <%= ENV['EC2_AZ'] %>
  aws_ssh_key_id: <%= ENV['EC2_SSH_KEY_ID'] %>
  instance_type: <%= ENV['EC2_INSTANCE_TYPE'] %>
  region: <%= ENV['EC2_REGION'] %>
  require_chef_omnibus: <%= ENV['REQUIRE_CHEF_OMNIBUS'] %>
  retryable_tries: 240
  security_group_ids: [<%= ENV['EC2_SG'] %>]
  subnet_id: <%= ENV['EC2_SUBNET_ID'] %>
  tags: {
    "Name": <%= ENV['COOKBOOK'] %>
  }

provisioner:
  name: chef_zero

platforms:
  - name: windows
    driver:
      image_search:
        "name": <%= ENV['EC2_IMAGE_NAME'] %>
    transport:
      name: winrm
      password: <%= ENV['WIN_PASS'] %>
      username: <%= ENV['WIN_USER'] %>

suites:
  - name: <%= ENV['COOKBOOK'] %>
    run_list:
      - recipe[<%= ENV['COOKBOOK'] %>::default]
